# 전치 행렬(transposed matrix)

- 기존 행렬의 행과 열을 바꾼 행렬
- 기존 행렬을 전치 행렬로 변환하면 행렬의 크기도 바뀌게 된다.</br>
$ u_{ij} \rightarrow u_{ji} $

## 전치 행렬의 성질
1. $(A^T)^T = A$

2. $(aA)^T = aA^T$ (여기서 $a$는 스칼라)

3. $(A + B)^T = A^T + B^T$

4. $(AB)^T = B^T A^T$

5. 만약 $A$가 가역행렬이면, $(A^{-1})^T = (A^T)^{-1}$




In [13]:
def transpose(A):
    """
    행렬의 전치 행렬
    입력값 : 전치 행렬을 구하고자 하는 행렬 A
    출력값 : 행렬 A의 전치 행렬 At
    """
    n = len(A)
    p = len(A[0])
    
    At = []
    for i in range(0, p):
        row = []
        for j in range(0, n):
            val = A[j][i]
            row.append(val)
        At.append(row)
    return At

In [3]:
A = [[1, 5], [3, 4], [6, 2]]
transpose(A)

[[1, 3, 6], [5, 4, 2]]

# 대칭 행렬(symmetric matrix)

- 기존 행렬과 전치 행렬이 동일한 정사각 행렬
- 행 번호와 열 번호를 바꾸어도 갑이 동일한 행렬이다.

## 대칭 행렬의 성질
- 대칭 행렬 간 덧셈과 뺄셈 결과 또한 대칭행렬
- 대칭 행렬 간 곱셈은 항상 대칭행렬이 아님
- 대칭 행렬의 거듭제곱은 대칭 행렬
- 어떤 행렬과 그 행렬의 전치 행렬은 대칭 행렬 

In [17]:
# 대칭행렬의 특징
def transpose(A):
    """
    행렬의 전치 행렬
    입력값 : 전치 행렬을 구하고자 하는 행렬 A
    출력값 : 행렬 A의 전치 행렬 At
    """
    n = len(A)
    p = len(A[0])
    
    At = []
    for i in range(0, p):
        row = []
        for j in range(0, n):
            val = A[j][i]
            row.append(val)
        At.append(row)
    return At

In [16]:
def matmul(A, B):
    """
    행렬의 행렬 곱
    입력값 : 행렬 곱을 수행할 행렬 A, B
    출력값 : 행렬 A와 행렬 B의 행렬 곱 결과인 행렬 res
    """
    
    n = len(A)
    p1 = len(A[0])
    p2 = len(B[0])
    
    res = []
    for i in range (0, n):
        row = []
        for j in range(0, p2):
            val = 0
            for k in range(0, p1):
                val += A[i][k] * B[k][j]
            row.append(val)
        res.append(row)
    return res

대칭 행렬 $A$의 전치 행렬 $A^T$가 기존 행렬 $A$와 동일한지 확인

In [11]:
A = [[1, 0, 2], [0, 2, 1], [2, 1, 1]]
A

[[1, 0, 2], [0, 2, 1], [2, 1, 1]]

In [12]:
At = transpose(A)
print(At)

[[1, 0, 2], [0, 2, 1], [2, 1, 1]]


In [13]:
A == At

True

행렬 $A$가 대칭행렬일 때 행렬의 거듭 제곱 또한 대칭 행렬인지를 확인

In [14]:
AA = A
for i in range(0, 9):
    AA = matmul(AA, A)
    print("행렬 A의", i+2, "제곱은", AA)

행렬 A의 2 제곱은 [[5, 2, 4], [2, 5, 3], [4, 3, 6]]
행렬 A의 3 제곱은 [[13, 8, 16], [8, 13, 12], [16, 12, 17]]
행렬 A의 4 제곱은 [[45, 32, 50], [32, 38, 41], [50, 41, 61]]
행렬 A의 5 제곱은 [[145, 114, 172], [114, 117, 143], [172, 143, 202]]
행렬 A의 6 제곱은 [[489, 400, 576], [400, 377, 488], [576, 488, 689]]
행렬 A의 7 제곱은 [[1641, 1376, 1954], [1376, 1242, 1665], [1954, 1665, 2329]]
행렬 A의 8 제곱은 [[5549, 4706, 6612], [4706, 4149, 5659], [6612, 5659, 7902]]
행렬 A의 9 제곱은 [[18773, 16024, 22416], [16024, 13957, 19220], [22416, 19220, 26785]]
행렬 A의 10 제곱은 [[63605, 54464, 75986], [54464, 47134, 65225], [75986, 65225, 90837]]


행렬 $A$와 행렬 $A$의 전치 행렬 $A^T$의 곱이 대칭 행렬이라는 점을 확인

In [14]:
A = [[1, 0, 3], [2, 1, 4], [0, 1, 1]]
At = transpose(A)
print(A)

[[1, 0, 3], [2, 1, 4], [0, 1, 1]]


In [15]:
print(At)

[[1, 2, 0], [0, 1, 1], [3, 4, 1]]


In [18]:
matmul(A, At)

[[10, 14, 3], [14, 21, 5], [3, 5, 2]]

In [19]:
# 곱하는 순서를 바꾸어도 대칭 행렬
matmul(At, A)

[[5, 2, 11], [2, 2, 5], [11, 5, 26]]

# 대각 행렬(diagonal matrix)

- 주 대각 원소가 아닌 원소가 0인 정사각 행렬
- 주로 $D$로 표기
- 정사각 행렬을 $PDP^{-1}$로 바꾸어 주어 구함
- $P$는 역행렬을 갖는 행렬

In [1]:
def diag(A):
    """
    행렬의 대각 행렬
    입력값 : 대각 행렬을 구하고자 하는 행렬 A
    출력값 : 행렬 A의 대각 행렬 D
    """
    n = len(A)
    D = []
    for i in range(0, n):
        row = []
        for j in range(0, n):
            if i == j:
                row.append(A[i][j])
            else:
                row.append(0)
        D.append(row)
    return D

In [3]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
diag(A)

[[1, 0, 0], [0, 5, 0], [0, 0, 9]]

In [6]:
def diag_ele(A):
    """
    대각 원소 구하기
    입력값 : 대각 원소를 구하고자 하는 행렬 A
    출력값 : 행렬 A의 대각 원소 리스트 d
    """
    n = len(A)
    d = []
    for i in range(0, n):
        d.append(A[i][i])
    return d

In [7]:
diag_ele(A)

[1, 5, 9]

In [8]:
def ele2diag(a):
    """
    대각 원소 -> 대각 행렬 변환
    입력값 : 대각 원소 리스트 a
    출력값 : 대각 원소 a를 이용해 생성한 nxn 대각 행렬 D
    n : 대각 원소 리스트 a의 길이
    """
    n = len(a)
    D = []
    for i in range(0, n):
        row = []
        for j in range(0, n):
            if i == j:
                row.append(a[i])
            else:
                row.append(0)
        D.append(row)
    return D

In [10]:
a = [1, 9, 5]

In [11]:
ele2diag(a)

[[1, 0, 0], [0, 9, 0], [0, 0, 5]]

일반 행렬에 대각행렬을 곱했을 때

In [20]:
 # D는 1행 1열이 2인 대각행렬
 A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
 D = ele2diag([2, 1, 1])
 print(A)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [21]:
print(D)

[[2, 0, 0], [0, 1, 0], [0, 0, 1]]


In [23]:
# 행렬 A의 1열에만 2가 곱해진 모습을 볼 수 있음
AD = matmul(A, D)
print(AD)

[[2, 2, 3], [8, 5, 6], [14, 8, 9]]


In [24]:
# 곱하는 순서를 바꿀 시 A의 1행에만 2가 곱해짐
DA = matmul(D, A)
print(DA)

[[2, 4, 6], [4, 5, 6], [7, 8, 9]]


In [25]:
 # D는 2행 2열이 3인 대각행렬
 A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
 D = ele2diag([1, 3, 1])
 print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [26]:
print(D)

[[1, 0, 0], [0, 3, 0], [0, 0, 1]]


In [27]:
# A의 2열에만 3이 곱해진 모습을 볼 수 있음
AD = matmul(A, D)
print(AD)

[[1, 6, 3], [4, 15, 6], [7, 24, 9]]


In [28]:
# 순서를 바꾸면 A의 2행에 3이 곱해진 결과를 볼 수 있음
DA = matmul(D, A)
print(DA)

[[1, 2, 3], [12, 15, 18], [7, 8, 9]]


In [31]:
# 2행 2열 값이 3이고 3행 3열 값이 4인 대각 행렬
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
D = ele2diag([1, 3, 4])
print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [32]:
# A의 2열에 3이 곱해지고 3열에 4가 곱해지는 것을 확인할 수 있음
AD = matmul(A, D)
print(AD)

[[1, 6, 12], [4, 15, 24], [7, 24, 36]]


In [ ]:
# 순서를 바꾸면 A의 2행에 3이 곱해지고 3행에 4가 곱해지는 것을 확인할 수 있음
DA = matmul(D, A)
print(DA)

### numpy 구현

In [33]:
import numpy as np

In [37]:
# 대각 행렬 구하기
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
D = np.diag(A)
print(D)
# A의 대각함수 D를 diag 함수 인자로 넣기
print(np.diag(D))

[1 5 9]
[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [38]:
# 대각 행렬과 행렬의 곱셈
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
D = np.diag([1, 3, 4])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
# 곱할 시 행렬 A의 2열에 3이 곱해지고 3열에 4가 곱해짐
AD = np.matmul(A,D)
print(AD)

[[ 1  6 12]
 [ 4 15 24]
 [ 7 24 36]]


In [42]:
# 순서를 바꿀 경우 행렬 A의 2행에 3이 곱해지고 3행에 4가 곱해짐
DA = np.matmul(D,A)
print(DA)

[[ 1  2  3]
 [12 15 18]
 [28 32 36]]


# 단위 행렬(identity matrix)

대각 원소가 1이고 그 밖의 나머지 원소는 모두 0인 대각 행렬

In [2]:
def identity(n):
    """
    단위 행렬 생성
    입력값 : 단위 행렬의 크기 n
    출력값 : nxn 단위 행렬 I
    """
    I = []
    for i in range(0, n):
        row = []
        for j in range(0, n):
            if i==j:
                row.append(1)
            else:
                row.append(0)
        I.append(row)
    return I

## 대각 행렬의 성질

# 영 행렬 (zero matrix)